language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: 
  - bash -ex .travis-opam.sh
  - opam pin add GT https://github.com/Kakadu/GT.git -n -y
  - opam install GT -y
  - make all
env:
  - OCAML_VERSION=4.04
os:
  - linux
